//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGJD_INA.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SGJD_INA.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to es-CR.
        /// </summary>
        internal static string CultureInfo {
            get {
                return ResourceManager.GetString("CultureInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al actualizar la carpeta física..
        /// </summary>
        internal static string ErrorActualizarCarpetaFisica {
            get {
                return ResourceManager.GetString("ErrorActualizarCarpetaFisica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al crear la carpeta física..
        /// </summary>
        internal static string ErrorCrearCarpetaFisica {
            get {
                return ResourceManager.GetString("ErrorCrearCarpetaFisica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al eliminar la carpeta física..
        /// </summary>
        internal static string ErrorEliminarCarpetaFisica {
            get {
                return ResourceManager.GetString("ErrorEliminarCarpetaFisica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El modelo es nulo..
        /// </summary>
        internal static string ModeloNulo {
            get {
                return ResourceManager.GetString("ModeloNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La solicitud es incorrecta..
        /// </summary>
        internal static string SolicitudIncorrecta {
            get {
                return ResourceManager.GetString("SolicitudIncorrecta", resourceCulture);
            }
        }
    }
}
