//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGJD_INA.Models.DA.EntityFramework.SGJD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SGJDEntities : DbContext
    {
        public SGJDEntities()
            : base("name=SGJDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SGJD_ACT_TAB_ACTAS_ACUERSOFT> SGJD_ACT_TAB_ACTAS_ACUERSOFT { get; set; }
        public virtual DbSet<SGJD_ACT_TAB_ACTAS_DETALLE_ACUERSOFT> SGJD_ACT_TAB_ACTAS_DETALLE_ACUERSOFT { get; set; }
        public virtual DbSet<SGJD_ACT_TAB_ASISTENTES_SESION> SGJD_ACT_TAB_ASISTENTES_SESION { get; set; }
        public virtual DbSet<SGJD_ACT_TAB_MIEMBROS_JUNTA_DIRECTIVA> SGJD_ACT_TAB_MIEMBROS_JUNTA_DIRECTIVA { get; set; }
        public virtual DbSet<SGJD_ACT_TAB_ORDENES_DIA> SGJD_ACT_TAB_ORDENES_DIA { get; set; }
        public virtual DbSet<SGJD_ACT_TAB_OTROS_ASISTENTES_SESION> SGJD_ACT_TAB_OTROS_ASISTENTES_SESION { get; set; }
        public virtual DbSet<SGJD_ACT_TAB_SESIONES> SGJD_ACT_TAB_SESIONES { get; set; }
        public virtual DbSet<SGJD_ACT_TAB_TOMOS> SGJD_ACT_TAB_TOMOS { get; set; }
        public virtual DbSet<SGJD_ACT_TAB_USUARIOS_ARTICULO> SGJD_ACT_TAB_USUARIOS_ARTICULO { get; set; }
        public virtual DbSet<SGJD_ACU_TAB_ACUERDOS> SGJD_ACU_TAB_ACUERDOS { get; set; }
        public virtual DbSet<SGJD_ACU_TAB_AVANCES> SGJD_ACU_TAB_AVANCES { get; set; }
        public virtual DbSet<SGJD_ACU_TAB_CORREOS_ADICIONALES> SGJD_ACU_TAB_CORREOS_ADICIONALES { get; set; }
        public virtual DbSet<SGJD_ACU_TAB_CORREOS_UNIDADES_ACUERDO> SGJD_ACU_TAB_CORREOS_UNIDADES_ACUERDO { get; set; }
        public virtual DbSet<SGJD_ACU_TAB_ELEMENTOS_RELACIONADOS> SGJD_ACU_TAB_ELEMENTOS_RELACIONADOS { get; set; }
        public virtual DbSet<SGJD_ACU_TAB_SEGUIMIENTOS> SGJD_ACU_TAB_SEGUIMIENTOS { get; set; }
        public virtual DbSet<SGJD_ACU_TAB_UNIDADES_INFORMACION_PREDETERMINADAS> SGJD_ACU_TAB_UNIDADES_INFORMACION_PREDETERMINADAS { get; set; }
        public virtual DbSet<SGJD_ACU_TAB_VOTACIONES_ACUERDO> SGJD_ACU_TAB_VOTACIONES_ACUERDO { get; set; }
        public virtual DbSet<SGJD_ADM_TAB_ARCHIVOS_ADJUNTOS> SGJD_ADM_TAB_ARCHIVOS_ADJUNTOS { get; set; }
        public virtual DbSet<SGJD_ADM_TAB_AUDIOS> SGJD_ADM_TAB_AUDIOS { get; set; }
        public virtual DbSet<SGJD_ADM_TAB_AVISOS> SGJD_ADM_TAB_AVISOS { get; set; }
        public virtual DbSet<SGJD_ADM_TAB_AYUDA_USUARIO> SGJD_ADM_TAB_AYUDA_USUARIO { get; set; }
        public virtual DbSet<SGJD_ADM_TAB_BITACORA> SGJD_ADM_TAB_BITACORA { get; set; }
        public virtual DbSet<SGJD_ADM_TAB_CORREOS_USUARIO> SGJD_ADM_TAB_CORREOS_USUARIO { get; set; }
        public virtual DbSet<SGJD_ADM_TAB_ENCABEZADO_PIEPAGINA> SGJD_ADM_TAB_ENCABEZADO_PIEPAGINA { get; set; }
        public virtual DbSet<SGJD_ADM_TAB_ESTADOS> SGJD_ADM_TAB_ESTADOS { get; set; }
        public virtual DbSet<SGJD_ADM_TAB_PARAMETROS_EDICION> SGJD_ADM_TAB_PARAMETROS_EDICION { get; set; }
        public virtual DbSet<SGJD_ADM_TAB_PARAMETROS_GENERALES> SGJD_ADM_TAB_PARAMETROS_GENERALES { get; set; }
        public virtual DbSet<SGJD_ADM_TAB_REPOSITORIOS> SGJD_ADM_TAB_REPOSITORIOS { get; set; }
        public virtual DbSet<SGJD_ADM_TAB_RESPALDOS> SGJD_ADM_TAB_RESPALDOS { get; set; }
        public virtual DbSet<SGJD_ADM_TAB_ROLES> SGJD_ADM_TAB_ROLES { get; set; }
        public virtual DbSet<SGJD_ADM_TAB_SECCIONES> SGJD_ADM_TAB_SECCIONES { get; set; }
        public virtual DbSet<SGJD_ADM_TAB_TELEFONOS_USUARIO> SGJD_ADM_TAB_TELEFONOS_USUARIO { get; set; }
        public virtual DbSet<SGJD_ADM_TAB_TIPOS_APROBACION> SGJD_ADM_TAB_TIPOS_APROBACION { get; set; }
        public virtual DbSet<SGJD_ADM_TAB_TIPOS_ARCHIVO> SGJD_ADM_TAB_TIPOS_ARCHIVO { get; set; }
        public virtual DbSet<SGJD_ADM_TAB_TIPOS_OBJETO> SGJD_ADM_TAB_TIPOS_OBJETO { get; set; }
        public virtual DbSet<SGJD_ADM_TAB_TIPOS_SESION> SGJD_ADM_TAB_TIPOS_SESION { get; set; }
        public virtual DbSet<SGJD_ADM_TAB_TIPOS_USUARIO> SGJD_ADM_TAB_TIPOS_USUARIO { get; set; }
        public virtual DbSet<SGJD_ADM_TAB_UNIDADES> SGJD_ADM_TAB_UNIDADES { get; set; }
        public virtual DbSet<SGJD_ADM_TAB_USUARIOS> SGJD_ADM_TAB_USUARIOS { get; set; }
        public virtual DbSet<SGJD_ADM_TAB_VISTAS> SGJD_ADM_TAB_VISTAS { get; set; }
        public virtual DbSet<SGJD_ADM_TAB_VISTAS_PERFIL> SGJD_ADM_TAB_VISTAS_PERFIL { get; set; }
        public virtual DbSet<SGJD_ADM_TAB_ERRORES> SGJD_ADM_TAB_ERRORES { get; set; }
        public virtual DbSet<SGJD_ACT_TAB_ARTICULOS> SGJD_ACT_TAB_ARTICULOS { get; set; }
        public virtual DbSet<SGJD_ACT_TAB_CAPITULOS> SGJD_ACT_TAB_CAPITULOS { get; set; }
        public virtual DbSet<SGJD_ACT_TAB_TEMAS> SGJD_ACT_TAB_TEMAS { get; set; }
        public virtual DbSet<SGJD_ACT_TAB_ACTAS> SGJD_ACT_TAB_ACTAS { get; set; }
    }
}
