//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGJD_INA.Models.DA.EntityFramework.SGJD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SGJD_ADM_TAB_AUDIOS
    {
        public int LLP_Id { get; set; }
        public int LLF_IdActa { get; set; }
        public string Nombre { get; set; }
        public string UrlAudio { get; set; }
        public string Transcripcion { get; set; }
    
        public virtual SGJD_ACT_TAB_ACTAS SGJD_ACT_TAB_ACTAS { get; set; }
    }
}
