//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGJD_INA.Models.DA.EntityFramework.SGJD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SGJD_ACT_TAB_ACTAS_ACUERSOFT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SGJD_ACT_TAB_ACTAS_ACUERSOFT()
        {
            this.SGJD_ACT_TAB_ACTAS_DETALLE_ACUERSOFT = new HashSet<SGJD_ACT_TAB_ACTAS_DETALLE_ACUERSOFT>();
        }
    
        public int LLP_Id { get; set; }
        public string Numero_Acta { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Lugar { get; set; }
        public Nullable<int> Tipo_Sesion { get; set; }
        public string Preside { get; set; }
        public string Secretario { get; set; }
        public Nullable<int> Estado { get; set; }
        public Nullable<System.DateTime> Fecha_creacion { get; set; }
        public string Tipo_Documento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SGJD_ACT_TAB_ACTAS_DETALLE_ACUERSOFT> SGJD_ACT_TAB_ACTAS_DETALLE_ACUERSOFT { get; set; }
    }
}
