//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGJD_INA.Models.DA.EntityFramework.SGJD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SGJD_ADM_TAB_ERRORES
    {
        public int LLP_Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Error { get; set; }
        public string Nombre_Archivo { get; set; }
        public string Nombre_Metodo { get; set; }
        public string Codigo_Excepcion { get; set; }
        public Nullable<int> Linea_Error { get; set; }
    }
}
