//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGJD_INA.Models.DA.EntityFramework.SGJD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SGJD_ADM_TAB_USUARIOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SGJD_ADM_TAB_USUARIOS()
        {
            this.SGJD_ACT_TAB_ASISTENTES_SESION = new HashSet<SGJD_ACT_TAB_ASISTENTES_SESION>();
            this.SGJD_ACT_TAB_SESIONES = new HashSet<SGJD_ACT_TAB_SESIONES>();
            this.SGJD_ACT_TAB_TOMOS = new HashSet<SGJD_ACT_TAB_TOMOS>();
            this.SGJD_ACT_TAB_TOMOS1 = new HashSet<SGJD_ACT_TAB_TOMOS>();
            this.SGJD_ACT_TAB_USUARIOS_ARTICULO = new HashSet<SGJD_ACT_TAB_USUARIOS_ARTICULO>();
            this.SGJD_ACU_TAB_AVANCES = new HashSet<SGJD_ACU_TAB_AVANCES>();
            this.SGJD_ADM_TAB_BITACORA = new HashSet<SGJD_ADM_TAB_BITACORA>();
            this.SGJD_ADM_TAB_CORREOS_USUARIO = new HashSet<SGJD_ADM_TAB_CORREOS_USUARIO>();
            this.SGJD_ADM_TAB_RESPALDOS = new HashSet<SGJD_ADM_TAB_RESPALDOS>();
            this.SGJD_ADM_TAB_TELEFONOS_USUARIO = new HashSet<SGJD_ADM_TAB_TELEFONOS_USUARIO>();
            this.SGJD_ADM_TAB_ROLES = new HashSet<SGJD_ADM_TAB_ROLES>();
            this.SGJD_ADM_TAB_AVISOS = new HashSet<SGJD_ADM_TAB_AVISOS>();
            this.SGJD_ADM_TAB_AVISOS1 = new HashSet<SGJD_ADM_TAB_AVISOS>();
            this.SGJD_ACT_TAB_ACTAS = new HashSet<SGJD_ACT_TAB_ACTAS>();
            this.SGJD_ACT_TAB_ACTAS1 = new HashSet<SGJD_ACT_TAB_ACTAS>();
        }
    
        public string LLP_Id { get; set; }
        public string Cedula { get; set; }
        public Nullable<System.DateTime> UltimaSesion { get; set; }
        public bool Activo { get; set; }
        public string Email { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string UserName { get; set; }
        public string Nombre { get; set; }
        public int LLF_IdTipoUsuario { get; set; }
        public int LLF_IdUnidad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SGJD_ACT_TAB_ASISTENTES_SESION> SGJD_ACT_TAB_ASISTENTES_SESION { get; set; }
        public virtual SGJD_ACT_TAB_MIEMBROS_JUNTA_DIRECTIVA SGJD_ACT_TAB_MIEMBROS_JUNTA_DIRECTIVA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SGJD_ACT_TAB_SESIONES> SGJD_ACT_TAB_SESIONES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SGJD_ACT_TAB_TOMOS> SGJD_ACT_TAB_TOMOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SGJD_ACT_TAB_TOMOS> SGJD_ACT_TAB_TOMOS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SGJD_ACT_TAB_USUARIOS_ARTICULO> SGJD_ACT_TAB_USUARIOS_ARTICULO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SGJD_ACU_TAB_AVANCES> SGJD_ACU_TAB_AVANCES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SGJD_ADM_TAB_BITACORA> SGJD_ADM_TAB_BITACORA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SGJD_ADM_TAB_CORREOS_USUARIO> SGJD_ADM_TAB_CORREOS_USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SGJD_ADM_TAB_RESPALDOS> SGJD_ADM_TAB_RESPALDOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SGJD_ADM_TAB_TELEFONOS_USUARIO> SGJD_ADM_TAB_TELEFONOS_USUARIO { get; set; }
        public virtual SGJD_ADM_TAB_TIPOS_USUARIO SGJD_ADM_TAB_TIPOS_USUARIO { get; set; }
        public virtual SGJD_ADM_TAB_UNIDADES SGJD_ADM_TAB_UNIDADES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SGJD_ADM_TAB_ROLES> SGJD_ADM_TAB_ROLES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SGJD_ADM_TAB_AVISOS> SGJD_ADM_TAB_AVISOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SGJD_ADM_TAB_AVISOS> SGJD_ADM_TAB_AVISOS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SGJD_ACT_TAB_ACTAS> SGJD_ACT_TAB_ACTAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SGJD_ACT_TAB_ACTAS> SGJD_ACT_TAB_ACTAS1 { get; set; }
    }
}
