//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGJD_INA.Models.DA.EntityFramework.SGJD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SGJD_ADM_TAB_TIPOS_APROBACION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SGJD_ADM_TAB_TIPOS_APROBACION()
        {
            this.SGJD_ACU_TAB_ACUERDOS = new HashSet<SGJD_ACU_TAB_ACUERDOS>();
        }
    
        public int LLP_Id { get; set; }
        public string Nombre { get; set; }
        public string Mensaje { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SGJD_ACU_TAB_ACUERDOS> SGJD_ACU_TAB_ACUERDOS { get; set; }
    }
}
