//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGJD_INA.Models.DA.EntityFramework.SGJD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SGJD_ADM_TAB_ENCABEZADO_PIEPAGINA
    {
        public int LLP_Id { get; set; }
        public int LLF_IdTipoObjeto { get; set; }
        public string Encabezado { get; set; }
        public string PiePagina { get; set; }
    
        public virtual SGJD_ADM_TAB_TIPOS_OBJETO SGJD_ADM_TAB_TIPOS_OBJETO { get; set; }
    }
}
