//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGJD_INA.Models.DA.EntityFramework.SGJD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SGJD_ACU_TAB_UNIDADES_INFORMACION_PREDETERMINADAS
    {
        public int LLF_IdUnidad { get; set; }
    
        public virtual SGJD_ADM_TAB_UNIDADES SGJD_ADM_TAB_UNIDADES { get; set; }
    }
}
