//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGJD_INA.Models.DA.EntityFramework.SGJD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SGJD_ADM_TAB_UNIDADES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SGJD_ADM_TAB_UNIDADES()
        {
            this.SGJD_ACU_TAB_CORREOS_UNIDADES_ACUERDO = new HashSet<SGJD_ACU_TAB_CORREOS_UNIDADES_ACUERDO>();
            this.SGJD_ADM_TAB_AVISOS = new HashSet<SGJD_ADM_TAB_AVISOS>();
            this.SGJD_ADM_TAB_USUARIOS = new HashSet<SGJD_ADM_TAB_USUARIOS>();
            this.SGJD_ACU_TAB_ACUERDOS = new HashSet<SGJD_ACU_TAB_ACUERDOS>();
            this.SGJD_ACU_TAB_SEGUIMIENTOS = new HashSet<SGJD_ACU_TAB_SEGUIMIENTOS>();
            this.SGJD_ACU_TAB_ACUERDOS1 = new HashSet<SGJD_ACU_TAB_ACUERDOS>();
        }
    
        public int LLP_Id { get; set; }
        public string Nombre { get; set; }
        public string Correo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SGJD_ACU_TAB_CORREOS_UNIDADES_ACUERDO> SGJD_ACU_TAB_CORREOS_UNIDADES_ACUERDO { get; set; }
        public virtual SGJD_ACU_TAB_UNIDADES_INFORMACION_PREDETERMINADAS SGJD_ACU_TAB_UNIDADES_INFORMACION_PREDETERMINADAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SGJD_ADM_TAB_AVISOS> SGJD_ADM_TAB_AVISOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SGJD_ADM_TAB_USUARIOS> SGJD_ADM_TAB_USUARIOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SGJD_ACU_TAB_ACUERDOS> SGJD_ACU_TAB_ACUERDOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SGJD_ACU_TAB_SEGUIMIENTOS> SGJD_ACU_TAB_SEGUIMIENTOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SGJD_ACU_TAB_ACUERDOS> SGJD_ACU_TAB_ACUERDOS1 { get; set; }
    }
}
