//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGJD_INA.Models.DA.EntityFramework.SGJD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SGJD_ACT_TAB_SESIONES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SGJD_ACT_TAB_SESIONES()
        {
            this.SGJD_ACT_TAB_ASISTENTES_SESION = new HashSet<SGJD_ACT_TAB_ASISTENTES_SESION>();
            this.SGJD_ACT_TAB_ORDENES_DIA = new HashSet<SGJD_ACT_TAB_ORDENES_DIA>();
            this.SGJD_ACT_TAB_OTROS_ASISTENTES_SESION = new HashSet<SGJD_ACT_TAB_OTROS_ASISTENTES_SESION>();
            this.SGJD_ACT_TAB_ACTAS = new HashSet<SGJD_ACT_TAB_ACTAS>();
            this.SGJD_ACT_TAB_ACTAS1 = new HashSet<SGJD_ACT_TAB_ACTAS>();
        }
    
        public int LLP_Id { get; set; }
        public int Numero { get; set; }
        public System.DateTime FechaHora { get; set; }
        public int LLF_IdTipoSesion { get; set; }
        public string LLF_IdUsuario { get; set; }
        public int LLF_IdEstado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SGJD_ACT_TAB_ASISTENTES_SESION> SGJD_ACT_TAB_ASISTENTES_SESION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SGJD_ACT_TAB_ORDENES_DIA> SGJD_ACT_TAB_ORDENES_DIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SGJD_ACT_TAB_OTROS_ASISTENTES_SESION> SGJD_ACT_TAB_OTROS_ASISTENTES_SESION { get; set; }
        public virtual SGJD_ADM_TAB_ESTADOS SGJD_ADM_TAB_ESTADOS { get; set; }
        public virtual SGJD_ADM_TAB_TIPOS_SESION SGJD_ADM_TAB_TIPOS_SESION { get; set; }
        public virtual SGJD_ADM_TAB_USUARIOS SGJD_ADM_TAB_USUARIOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SGJD_ACT_TAB_ACTAS> SGJD_ACT_TAB_ACTAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SGJD_ACT_TAB_ACTAS> SGJD_ACT_TAB_ACTAS1 { get; set; }
    }
}
