//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGJD_INA.Models.DA.EntityFramework.SGJD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SGJD_ACT_TAB_OTROS_ASISTENTES_SESION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SGJD_ACT_TAB_OTROS_ASISTENTES_SESION()
        {
            this.SGJD_ACT_TAB_USUARIOS_ARTICULO = new HashSet<SGJD_ACT_TAB_USUARIOS_ARTICULO>();
        }
    
        public int LLP_Id { get; set; }
        public int LLF_IdSesion { get; set; }
        public int LLF_IdTipoUsuario { get; set; }
        public string Nombre { get; set; }
        public string Puesto { get; set; }
        public string HoraInicio { get; set; }
        public string HoraFin { get; set; }
    
        public virtual SGJD_ACT_TAB_SESIONES SGJD_ACT_TAB_SESIONES { get; set; }
        public virtual SGJD_ADM_TAB_TIPOS_USUARIO SGJD_ADM_TAB_TIPOS_USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SGJD_ACT_TAB_USUARIOS_ARTICULO> SGJD_ACT_TAB_USUARIOS_ARTICULO { get; set; }
    }
}
