//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGJD_INA.Models.DA.EntityFramework.SGJD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SGJD_ACT_TAB_ACTAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SGJD_ACT_TAB_ACTAS()
        {
            this.SGJD_ADM_TAB_AUDIOS = new HashSet<SGJD_ADM_TAB_AUDIOS>();
            this.SGJD_ACT_TAB_CAPITULOS = new HashSet<SGJD_ACT_TAB_CAPITULOS>();
            this.SGJD_ACU_TAB_ELEMENTOS_RELACIONADOS = new HashSet<SGJD_ACU_TAB_ELEMENTOS_RELACIONADOS>();
        }
    
        public int LLP_Id { get; set; }
        public int LLF_IdSesion { get; set; }
        public int LLF_IdTomo { get; set; }
        public int LLF_IdEstado { get; set; }
        public string Encabezado { get; set; }
        public string Observacion { get; set; }
        public string UrlActaFirmada { get; set; }
        public string ParrafoCierre { get; set; }
        public int NumeroPaginasPDF { get; set; }
        public string LLF_IdUsuarioPreside { get; set; }
        public string LLF_IdSecretario { get; set; }
        public Nullable<int> LLF_IdSesionAprobada { get; set; }
        public string NotaVotosDisidentes { get; set; }
    
        public virtual SGJD_ADM_TAB_ESTADOS SGJD_ADM_TAB_ESTADOS { get; set; }
        public virtual SGJD_ACT_TAB_SESIONES SGJD_ACT_TAB_SESIONES { get; set; }
        public virtual SGJD_ACT_TAB_SESIONES SGJD_ACT_TAB_SESIONES1 { get; set; }
        public virtual SGJD_ACT_TAB_TOMOS SGJD_ACT_TAB_TOMOS { get; set; }
        public virtual SGJD_ADM_TAB_USUARIOS SGJD_ADM_TAB_USUARIOS { get; set; }
        public virtual SGJD_ADM_TAB_USUARIOS SGJD_ADM_TAB_USUARIOS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SGJD_ADM_TAB_AUDIOS> SGJD_ADM_TAB_AUDIOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SGJD_ACT_TAB_CAPITULOS> SGJD_ACT_TAB_CAPITULOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SGJD_ACU_TAB_ELEMENTOS_RELACIONADOS> SGJD_ACU_TAB_ELEMENTOS_RELACIONADOS { get; set; }
    }
}
