//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGJD_INA.Models.DA.EntityFramework.SGJD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SGJD_ACU_TAB_ACUERDOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SGJD_ACU_TAB_ACUERDOS()
        {
            this.SGJD_ACU_TAB_SEGUIMIENTOS = new HashSet<SGJD_ACU_TAB_SEGUIMIENTOS>();
            this.SGJD_ACU_TAB_VOTACIONES_ACUERDO = new HashSet<SGJD_ACU_TAB_VOTACIONES_ACUERDO>();
            this.SGJD_ACU_TAB_ELEMENTOS_RELACIONADOS = new HashSet<SGJD_ACU_TAB_ELEMENTOS_RELACIONADOS>();
            this.SGJD_ACU_TAB_CORREOS_ADICIONALES = new HashSet<SGJD_ACU_TAB_CORREOS_ADICIONALES>();
            this.SGJD_ADM_TAB_UNIDADES = new HashSet<SGJD_ADM_TAB_UNIDADES>();
            this.SGJD_ADM_TAB_UNIDADES1 = new HashSet<SGJD_ADM_TAB_UNIDADES>();
        }
    
        public int LLP_Id { get; set; }
        public int LLF_IdArticulo { get; set; }
        public int LLF_IdEstado { get; set; }
        public int LLF_IdTipoAprobacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int NumeroAcuerdo { get; set; }
        public string Titulo { get; set; }
        public bool Firme { get; set; }
        public Nullable<System.DateTime> FechaFirmeza { get; set; }
        public string Asunto { get; set; }
        public int NumeroVersion { get; set; }
        public string Detalle { get; set; }
        public string Observaciones { get; set; }
        public int TipoSeguimiento { get; set; }
        public bool Revision { get; set; }
        public string DetalleConsiderando { get; set; }
        public string DetallePorTanto { get; set; }
        public string UrlAcuerdoFirmado { get; set; }
        public string ObservacionVotaciones { get; set; }
        public Nullable<System.DateTime> FechaNotificacion { get; set; }
    
        public virtual SGJD_ADM_TAB_ESTADOS SGJD_ADM_TAB_ESTADOS { get; set; }
        public virtual SGJD_ADM_TAB_TIPOS_APROBACION SGJD_ADM_TAB_TIPOS_APROBACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SGJD_ACU_TAB_SEGUIMIENTOS> SGJD_ACU_TAB_SEGUIMIENTOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SGJD_ACU_TAB_VOTACIONES_ACUERDO> SGJD_ACU_TAB_VOTACIONES_ACUERDO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SGJD_ACU_TAB_ELEMENTOS_RELACIONADOS> SGJD_ACU_TAB_ELEMENTOS_RELACIONADOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SGJD_ACU_TAB_CORREOS_ADICIONALES> SGJD_ACU_TAB_CORREOS_ADICIONALES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SGJD_ADM_TAB_UNIDADES> SGJD_ADM_TAB_UNIDADES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SGJD_ADM_TAB_UNIDADES> SGJD_ADM_TAB_UNIDADES1 { get; set; }
        public virtual SGJD_ACT_TAB_ARTICULOS SGJD_ACT_TAB_ARTICULOS { get; set; }
    }
}
