//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGJD_INA.Models.DA.EntityFramework.SGJD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SGJD_ACU_TAB_VOTACIONES_ACUERDO
    {
        public int LLP_Id { get; set; }
        public int LLF_IdAcuerdo { get; set; }
        public int LLF_IdAsistente { get; set; }
        public string TipoVotacion { get; set; }
    
        public virtual SGJD_ACT_TAB_ASISTENTES_SESION SGJD_ACT_TAB_ASISTENTES_SESION { get; set; }
        public virtual SGJD_ACU_TAB_ACUERDOS SGJD_ACU_TAB_ACUERDOS { get; set; }
    }
}
