//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGJD_INA.Models.DA.EntityFramework.SGJD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SGJD_ACT_TAB_TOMOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SGJD_ACT_TAB_TOMOS()
        {
            this.SGJD_ACT_TAB_ACTAS = new HashSet<SGJD_ACT_TAB_ACTAS>();
        }
    
        public int LLP_Id { get; set; }
        public int Numero { get; set; }
        public string Nombre { get; set; }
        public string ObservaciónApertura { get; set; }
        public string ObservacionCierre { get; set; }
        public string LLF_IdUsuarioApertura { get; set; }
        public string LLF_IdUsuarioCierre { get; set; }
        public System.DateTime FechaApertura { get; set; }
        public Nullable<System.DateTime> FechaCierre { get; set; }
        public int LLF_IdEstado { get; set; }
        public int Asiento { get; set; }
        public string UrlOficioApertura { get; set; }
        public string UrlOficioCierre { get; set; }
        public string ObservacionesMedianteOficio { get; set; }
    
        public virtual SGJD_ADM_TAB_ESTADOS SGJD_ADM_TAB_ESTADOS { get; set; }
        public virtual SGJD_ADM_TAB_USUARIOS SGJD_ADM_TAB_USUARIOS { get; set; }
        public virtual SGJD_ADM_TAB_USUARIOS SGJD_ADM_TAB_USUARIOS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SGJD_ACT_TAB_ACTAS> SGJD_ACT_TAB_ACTAS { get; set; }
    }
}
