//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGJD_INA.Models.DA.EntityFramework.SGJD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SGJD_ADM_TAB_ESTADOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SGJD_ADM_TAB_ESTADOS()
        {
            this.SGJD_ACT_TAB_ORDENES_DIA = new HashSet<SGJD_ACT_TAB_ORDENES_DIA>();
            this.SGJD_ACT_TAB_SESIONES = new HashSet<SGJD_ACT_TAB_SESIONES>();
            this.SGJD_ACT_TAB_TOMOS = new HashSet<SGJD_ACT_TAB_TOMOS>();
            this.SGJD_ACU_TAB_ACUERDOS = new HashSet<SGJD_ACU_TAB_ACUERDOS>();
            this.SGJD_ACU_TAB_SEGUIMIENTOS = new HashSet<SGJD_ACU_TAB_SEGUIMIENTOS>();
            this.SGJD_ACT_TAB_TEMAS = new HashSet<SGJD_ACT_TAB_TEMAS>();
            this.SGJD_ACT_TAB_ACTAS = new HashSet<SGJD_ACT_TAB_ACTAS>();
        }
    
        public int LLP_Id { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string CodigoEstado { get; set; }
        public int LLF_IdTipoObjeto { get; set; }
        public int LLF_IdAviso { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SGJD_ACT_TAB_ORDENES_DIA> SGJD_ACT_TAB_ORDENES_DIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SGJD_ACT_TAB_SESIONES> SGJD_ACT_TAB_SESIONES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SGJD_ACT_TAB_TOMOS> SGJD_ACT_TAB_TOMOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SGJD_ACU_TAB_ACUERDOS> SGJD_ACU_TAB_ACUERDOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SGJD_ACU_TAB_SEGUIMIENTOS> SGJD_ACU_TAB_SEGUIMIENTOS { get; set; }
        public virtual SGJD_ADM_TAB_AVISOS SGJD_ADM_TAB_AVISOS { get; set; }
        public virtual SGJD_ADM_TAB_TIPOS_OBJETO SGJD_ADM_TAB_TIPOS_OBJETO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SGJD_ACT_TAB_TEMAS> SGJD_ACT_TAB_TEMAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SGJD_ACT_TAB_ACTAS> SGJD_ACT_TAB_ACTAS { get; set; }
    }
}
