//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGJD_INA.Models.DA.EntityFramework.SGJD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SGJD_ACU_TAB_SEGUIMIENTOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SGJD_ACU_TAB_SEGUIMIENTOS()
        {
            this.SGJD_ACU_TAB_AVANCES = new HashSet<SGJD_ACU_TAB_AVANCES>();
            this.SGJD_ACU_TAB_ELEMENTOS_RELACIONADOS = new HashSet<SGJD_ACU_TAB_ELEMENTOS_RELACIONADOS>();
            this.SGJD_ADM_TAB_UNIDADES = new HashSet<SGJD_ADM_TAB_UNIDADES>();
        }
    
        public int LLP_Id { get; set; }
        public int LLF_IdAcuerdo { get; set; }
        public int LLF_IdEstado { get; set; }
        public int PorcentajeAvance { get; set; }
        public Nullable<System.DateTime> FechaNotificacion { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public int PlazoDias { get; set; }
        public string Observaciones { get; set; }
    
        public virtual SGJD_ACU_TAB_ACUERDOS SGJD_ACU_TAB_ACUERDOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SGJD_ACU_TAB_AVANCES> SGJD_ACU_TAB_AVANCES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SGJD_ACU_TAB_ELEMENTOS_RELACIONADOS> SGJD_ACU_TAB_ELEMENTOS_RELACIONADOS { get; set; }
        public virtual SGJD_ADM_TAB_ESTADOS SGJD_ADM_TAB_ESTADOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SGJD_ADM_TAB_UNIDADES> SGJD_ADM_TAB_UNIDADES { get; set; }
    }
}
