//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGJD_INA.Models.DA.EntityFramework.SGJD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SGJD_ADM_TAB_PARAMETROS_EDICION
    {
        public int LLP_Id { get; set; }
        public int LLF_IdTipoObjeto { get; set; }
        public string FuenteTitulo { get; set; }
        public int TamanoTitulo { get; set; }
        public string EstiloFuenteTitulo { get; set; }
        public string FuenteContenido { get; set; }
        public int TamanoContenido { get; set; }
        public string EstiloFuenteContenido { get; set; }
        public string AlineacionParrafoTitulo { get; set; }
        public string AlineacionParrafoContenido { get; set; }
    
        public virtual SGJD_ADM_TAB_TIPOS_OBJETO SGJD_ADM_TAB_TIPOS_OBJETO { get; set; }
    }
}
