//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGJD_INA.Models.DA.EntityFramework.SGJD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SGJD_ACT_TAB_USUARIOS_ARTICULO
    {
        public int LLP_Id { get; set; }
        public string LLF_IdUsuario { get; set; }
        public Nullable<int> LLF_IdOtroAsistente { get; set; }
        public int LLF_IdArticulo { get; set; }
    
        public virtual SGJD_ACT_TAB_OTROS_ASISTENTES_SESION SGJD_ACT_TAB_OTROS_ASISTENTES_SESION { get; set; }
        public virtual SGJD_ADM_TAB_USUARIOS SGJD_ADM_TAB_USUARIOS { get; set; }
        public virtual SGJD_ACT_TAB_ARTICULOS SGJD_ACT_TAB_ARTICULOS { get; set; }
    }
}
