//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGJD_INA.Models.DA.EntityFramework.SGJD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SGJD_ACU_TAB_AVANCES
    {
        public int LLP_Id { get; set; }
        public int LLF_IdSeguimientoAcuerdo { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string LLF_IdUsuario { get; set; }
    
        public virtual SGJD_ACU_TAB_SEGUIMIENTOS SGJD_ACU_TAB_SEGUIMIENTOS { get; set; }
        public virtual SGJD_ADM_TAB_USUARIOS SGJD_ADM_TAB_USUARIOS { get; set; }
    }
}
