//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGJD_INA.Models.DA.EntityFramework.SGJD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SGJD_ADM_TAB_AYUDA_USUARIO
    {
        public int LLP_Id { get; set; }
        public string NombreModulo { get; set; }
        public string NombreVista { get; set; }
        public string MensajeAyuda { get; set; }
        public string Abreviatura { get; set; }
    }
}
