//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGJD_INA.Models.DA.EntityFramework.SGJD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SGJD_ADM_TAB_ARCHIVOS_ADJUNTOS
    {
        public int LLP_Id { get; set; }
        public int LLF_IdTipoObjeto { get; set; }
        public int LLF_IdRepositorio { get; set; }
        public int IdObjeto { get; set; }
        public string Observacion { get; set; }
        public string UrlArchivo { get; set; }
        public int LLF_TipoArchivo { get; set; }
    
        public virtual SGJD_ADM_TAB_REPOSITORIOS SGJD_ADM_TAB_REPOSITORIOS { get; set; }
        public virtual SGJD_ADM_TAB_TIPOS_ARCHIVO SGJD_ADM_TAB_TIPOS_ARCHIVO { get; set; }
        public virtual SGJD_ADM_TAB_TIPOS_OBJETO SGJD_ADM_TAB_TIPOS_OBJETO { get; set; }
    }
}
