//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGJD_INA.Models.DA.EntityFramework.SGJD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SGJD_ADM_TAB_TIPOS_OBJETO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SGJD_ADM_TAB_TIPOS_OBJETO()
        {
            this.SGJD_ADM_TAB_ARCHIVOS_ADJUNTOS = new HashSet<SGJD_ADM_TAB_ARCHIVOS_ADJUNTOS>();
            this.SGJD_ADM_TAB_ENCABEZADO_PIEPAGINA = new HashSet<SGJD_ADM_TAB_ENCABEZADO_PIEPAGINA>();
            this.SGJD_ADM_TAB_ESTADOS = new HashSet<SGJD_ADM_TAB_ESTADOS>();
            this.SGJD_ADM_TAB_PARAMETROS_EDICION = new HashSet<SGJD_ADM_TAB_PARAMETROS_EDICION>();
        }
    
        public int LLP_Id { get; set; }
        public string Descripcion { get; set; }
        public string NombreTabla { get; set; }
        public bool ParametroEdicion { get; set; }
        public string Nomenclatura { get; set; }
        public int Consecutivo { get; set; }
        public bool ParametroEncabezadoPie { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SGJD_ADM_TAB_ARCHIVOS_ADJUNTOS> SGJD_ADM_TAB_ARCHIVOS_ADJUNTOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SGJD_ADM_TAB_ENCABEZADO_PIEPAGINA> SGJD_ADM_TAB_ENCABEZADO_PIEPAGINA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SGJD_ADM_TAB_ESTADOS> SGJD_ADM_TAB_ESTADOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SGJD_ADM_TAB_PARAMETROS_EDICION> SGJD_ADM_TAB_PARAMETROS_EDICION { get; set; }
    }
}
