//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGJD_INA.Models.DA.EntityFramework.SGJD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SGJD_ACT_TAB_ASISTENTES_SESION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SGJD_ACT_TAB_ASISTENTES_SESION()
        {
            this.SGJD_ACU_TAB_VOTACIONES_ACUERDO = new HashSet<SGJD_ACU_TAB_VOTACIONES_ACUERDO>();
        }
    
        public int LLP_Id { get; set; }
        public int LLF_IdSesion { get; set; }
        public string LLF_IdUsuario { get; set; }
        public string Tipo { get; set; }
        public string HoraInicio { get; set; }
        public string HoraFin { get; set; }
    
        public virtual SGJD_ACT_TAB_SESIONES SGJD_ACT_TAB_SESIONES { get; set; }
        public virtual SGJD_ADM_TAB_USUARIOS SGJD_ADM_TAB_USUARIOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SGJD_ACU_TAB_VOTACIONES_ACUERDO> SGJD_ACU_TAB_VOTACIONES_ACUERDO { get; set; }
    }
}
