//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGJD_INA.Models.DA.EntityFramework.SGJD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SGJD_ACT_TAB_ORDENES_DIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SGJD_ACT_TAB_ORDENES_DIA()
        {
            this.SGJD_ADM_TAB_SECCIONES = new HashSet<SGJD_ADM_TAB_SECCIONES>();
            this.SGJD_ACT_TAB_TEMAS = new HashSet<SGJD_ACT_TAB_TEMAS>();
        }
    
        public int LLP_Id { get; set; }
        public int LLF_IdSesion { get; set; }
        public int LLF_IdEstado { get; set; }
        public string Encabezado { get; set; }
    
        public virtual SGJD_ADM_TAB_ESTADOS SGJD_ADM_TAB_ESTADOS { get; set; }
        public virtual SGJD_ACT_TAB_SESIONES SGJD_ACT_TAB_SESIONES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SGJD_ADM_TAB_SECCIONES> SGJD_ADM_TAB_SECCIONES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SGJD_ACT_TAB_TEMAS> SGJD_ACT_TAB_TEMAS { get; set; }
    }
}
