//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGJD_INA.Models.DA.EntityFramework.SGJD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SGJD_ADM_TAB_VISTAS_PERFIL
    {
        public int LLF_IdVista { get; set; }
        public string LLF_IdRol { get; set; }
        public int Permiso { get; set; }
    
        public virtual SGJD_ADM_TAB_ROLES SGJD_ADM_TAB_ROLES { get; set; }
        public virtual SGJD_ADM_TAB_VISTAS SGJD_ADM_TAB_VISTAS { get; set; }
    }
}
