//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGJD_INA.Models.DA.EntityFramework.SGJD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SGJD_ACU_TAB_ELEMENTOS_RELACIONADOS
    {
        public int LLP_Id { get; set; }
        public Nullable<int> LLF_IdActa { get; set; }
        public Nullable<int> LLF_IdAcuerdo { get; set; }
        public int LLF_IdSeguimiento { get; set; }
        public string TipoElemento { get; set; }
    
        public virtual SGJD_ACU_TAB_ACUERDOS SGJD_ACU_TAB_ACUERDOS { get; set; }
        public virtual SGJD_ACU_TAB_SEGUIMIENTOS SGJD_ACU_TAB_SEGUIMIENTOS { get; set; }
        public virtual SGJD_ACT_TAB_ACTAS SGJD_ACT_TAB_ACTAS { get; set; }
    }
}
