//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGJD_INA.Models.DA.EntityFramework.SIRH
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_SIRH_FUNC_SIRIA
    {
        public decimal CEDULA { get; set; }
        public string NOMBRE_EMPLEADO { get; set; }
        public string CORREO { get; set; }
        public string USUARIO { get; set; }
    }
}
