--USE master

--CREATE DATABASE SGJD

USE SGJD

--CREATE TABLE SGJD_ADM_TAB_PERFIL (
CREATE TABLE AspNetRoles (
	Id NVARCHAR (128) NOT NULL, --Id de perfil para IDENTITY
	[Name] NVARCHAR (50) NOT NULL UNIQUE,
	Discriminator NVARCHAR(128) NOT NULL,
	CONSTRAINT LLP_Perfil PRIMARY KEY CLUSTERED (Id)
)

INSERT INTO AspNetRoles VALUES ('1', 'Administrador', 'SGJDIdentity')
INSERT INTO AspNetRoles VALUES ('2', 'Director', 'SGJDIdentity')

CREATE TABLE SGJD_ADM_TAB_VISTA (
	LLP_Id INT NOT NULL IDENTITY (1, 1),
	NombreVista NVARCHAR(100) NOT NULL,
	DireccionVista NVARCHAR(100) NOT NULL,
	CONSTRAINT LLP_Vista PRIMARY KEY CLUSTERED (LLP_Id ASC)
)

INSERT INTO SGJD_ADM_TAB_VISTA VALUES ('Módulo de Administración', '/Home/Administracion')
INSERT INTO SGJD_ADM_TAB_VISTA VALUES ('Módulo de Actas', '/Home/Actas')
INSERT INTO SGJD_ADM_TAB_VISTA VALUES ('Módulo de Acuerdos', '/Home/Acuerdos')

CREATE TABLE SGJD_ADM_TAB_VISTA_PERFIL (
	LLF_IdVista INT NOT NULL,
	LLF_IdPerfil NVARCHAR (128) NOT NULL,
	Permiso INT NOT NULL,
	CONSTRAINT LLP_VistaPerfil PRIMARY KEY CLUSTERED (LLF_IdVista, LLF_IdPerfil),
	CONSTRAINT LLF_VistaPerfil_Vista_LLF_IdVista FOREIGN KEY (LLF_IdVista) REFERENCES SGJD_ADM_TAB_VISTA (LLP_Id),
	CONSTRAINT LLF_VistaPerfil_AspNetRoles_LLF_IdPerfil FOREIGN KEY (LLF_IdPerfil) REFERENCES AspNetRoles (Id)
)

INSERT INTO SGJD_ADM_TAB_VISTA_PERFIL VALUES (1, '1', 7)
INSERT INTO SGJD_ADM_TAB_VISTA_PERFIL VALUES (1, '2', 5)

CREATE TABLE SGJD_ADM_TAB_TIPO_USUARIO (
	LLP_Id INT NOT NULL IDENTITY (1, 1),
	Nombre NVARCHAR(256) NOT NULL,
	CONSTRAINT LLP_TipoUsuario PRIMARY KEY CLUSTERED (LLP_Id ASC)
)

INSERT INTO SGJD_ADM_TAB_TIPO_USUARIO VALUES ('Administrativo')
INSERT INTO SGJD_ADM_TAB_TIPO_USUARIO VALUES ('Director')
INSERT INTO SGJD_ADM_TAB_TIPO_USUARIO VALUES ('Expositor')

CREATE TABLE SGJD_ADM_TAB_UNIDAD (
	LLP_Id INT NOT NULL IDENTITY (1, 1),
	Nombre NVARCHAR (50) NOT NULL,
	CONSTRAINT LLP_Unidad PRIMARY KEY CLUSTERED (LLP_Id ASC)
)

INSERT INTO SGJD_ADM_TAB_UNIDAD VALUES ('Gerencia General')
INSERT INTO SGJD_ADM_TAB_UNIDAD VALUES ('Presidencia Ejecutiva')
INSERT INTO SGJD_ADM_TAB_UNIDAD VALUES ('Secretaría Técnica de Junta Directiva')

CREATE TABLE SGJD_ADM_TAB_USUARIO (
	Id NVARCHAR (128) NOT NULL, --Id de usuario para IDENTITY
	IdOffice NVARCHAR (128) NULL, --Id de usuario Office 365
	LLF_IdTipoUsuario INT NOT NULL,
	LLF_IdUnidad INT NOT NULL,
	Cedula NVARCHAR (20) NOT NULL,
	[Name] NVARCHAR (50) NOT NULL,
	Email NVARCHAR (50) NOT NULL,
	UserName NVARCHAR (256) NOT NULL,
	PasswordHash NVARCHAR (128) NOT NULL,
	SecurityStamp NVARCHAR (128) NOT NULL,
	Activo BIT NOT NULL,
	UltimaSesion DATETIME NULL,
	CONSTRAINT LLP_Usuario PRIMARY KEY CLUSTERED (Id),
	CONSTRAINT LLF_Usuario_TipoUsuario_LLF_IdTipoUsuario FOREIGN KEY (LLF_IdTipoUsuario) REFERENCES SGJD_ADM_TAB_TIPO_USUARIO (LLP_Id),
	CONSTRAINT LLF_Usuario_Unidad_LLF_IdUnidad FOREIGN KEY (LLF_IdUnidad) REFERENCES SGJD_ADM_TAB_UNIDAD (LLP_Id)
)

INSERT INTO SGJD_ADM_TAB_USUARIO VALUES ('043164cd-8995-48c6-806d-6fc684388e71', 1, 1, '111490863', 'Sharon', 'Umaña', 'sumana@datasoft.co.cr', 'sumana@datasoft.co.cr', 'AB/zPqBHvlDmPOnfmmGErc6zE8wFO6wKvlhU/vyXhZR5ZrsoNVoAFSnID6Rv4szdig==', '8f6c3c1a-339a-4a92-ade9-4d38c009431d', 1, '20190228')
INSERT INTO SGJD_ADM_TAB_USUARIO VALUES ('81582e44-4e62-4a16-bf86-9103005613a4', 2, 2, '604300799', 'Sharel', 'Solis', 'gsolis@datasoft.co.cr', 'gsolis@datasoft.co.cr', 'ALjzKjzoyV3NIS/7dDyr7NfrpXX0Y1SRFv8lxxLDRI/x++iMHGHfqYBp/qHZ98q3hg===', '287e22d4-7e0c-4946-8d0c-0f1b104be458', 1, '20190228')
INSERT INTO SGJD_ADM_TAB_USUARIO VALUES ('f448c541-0fe8-4558-939b-795bc975701e', 2, 2, '144446666', 'Derian', 'Chavarría Zúñiga', 'dchavarria@datasoft.co.cr', 'dchavarria@datasoft.co.cr', 'ABXUSrwIx4lfsgi+z8vjNZ6PHatwjolvRemho72t6IXEWzy64XXWSzQHa7mXpYlMKQ==', '2e807fbb-d344-40b6-8902-d26e2c0e99b6', 1, '20190228' )
INSERT INTO SGJD_ADM_TAB_USUARIO VALUES ('fe69b9b4-13f6-423f-9e78-940953f0d45e', 1, 1, '206830685', 'Enmanuelle', 'Acuña Arguedas', 'eacuna@datasoft.co.cr', 'eacuna', 'ANHbprwphbv29jYCb/XfbEd6Kn5ungwhM4426VdeWI0fa0dysWEPWYreKSujCqmAog==', '439fbdc2-6d68-4c0b-b5ac-6a007f981853', 1, '20190228' )

CREATE TABLE SGJD_ADM_TAB_MIEMBROS_JD (
	LLF_IdUsuario NVARCHAR(128) NOT NULL UNIQUE,
	CONSTRAINT LLP_MiembrosJD PRIMARY KEY CLUSTERED (LLF_IdUsuario ASC),
	CONSTRAINT LLF_MiembrosJD_Usuario_LLF_IdUsuario FOREIGN KEY (LLF_IdUsuario) REFERENCES SGJD_ADM_TAB_USUARIO (Id)
)

CREATE TABLE SGJD_ADM_TAB_TIPO_OBJETO (
	LLP_Id INT NOT NULL IDENTITY (1, 1),	
	Descripcion NVARCHAR (50) NOT NULL UNIQUE,
	NombreTabla NVARCHAR (250) NOT NULL UNIQUE,
	ParametroEdicion BIT NOT NULL,
	ParametroEncabezadoPie BIT NOT NULL,
	Consecutivo INTEGER NOT NULL,
	Nomenclatura NVARCHAR (50) NOT NULL,
	CONSTRAINT LLP_TipoObjeto PRIMARY KEY CLUSTERED (LLP_Id ASC)
)

INSERT INTO SGJD_ADM_TAB_TIPO_OBJETO VALUES ('Capítulo', 'SGJD_ACT_TAB_CAPITULO', 1, 1, 'CAP')

CREATE TABLE SGJD_ADM_TAB_PARAMETRO_EDICION (
	LLP_Id INT NOT NULL IDENTITY (1, 1),
	LLF_IdTipoObjeto INT NOT NULL,
	FuenteTitulo NVARCHAR (50) NOT NULL,
	TamanoTitulo INT NOT NULL,
	EstiloFuenteTitulo NVARCHAR (20) NULL,
	AlineacionParrafoTitulo NVARCHAR (20) NULL,
	FuenteContenido NVARCHAR (50) NOT NULL,
	TamanoContenido INT NOT NULL,
	EstiloFuenteContenido NVARCHAR (20) NULL,
	AlineacionParrafoContenido NVARCHAR (20) NULL,
	CONSTRAINT LLP_ParametroEdicion PRIMARY KEY CLUSTERED (LLP_Id ASC),
	CONSTRAINT LLF_ParametroEdicion_TipoObjeto_LLF_IdTipoObjeto FOREIGN KEY (LLF_IdTipoObjeto) REFERENCES SGJD_ADM_TAB_TIPO_OBJETO (LLP_Id)
)

CREATE TABLE SGJD_ADM_TAB_ESTADO (
	LLP_Id INT NOT NULL IDENTITY (1, 1),
	LLF_IdTipoObjeto INT NOT NULL,
	LLF_IdAviso INT NOT NULL,
	Descripcion NVARCHAR (50) NOT NULL,
	CONSTRAINT LLP_Estado PRIMARY KEY CLUSTERED (LLP_Id ASC),
	CONSTRAINT LLF_Estado_TipoObjeto_LLF_IdTipoObjeto FOREIGN KEY (LLF_IdTipoObjeto) REFERENCES SGJD_ADM_TAB_TIPO_OBJETO (LLP_Id),
	CONSTRAINT LLF_Estado_Aviso_LLF_IdAviso FOREIGN KEY (LLF_IdAviso) REFERENCES SGJD_ADM_TAB_CONFIGURACION_AVISOS (LLP_Id)
)

CREATE TABLE SGJD_ADM_TAB_TIPO_SESION (
	LLP_Id INT NOT NULL IDENTITY (1, 1),
	Descripcion NVARCHAR (50) NOT NULL,
	CONSTRAINT LLP_TipoSesion PRIMARY KEY CLUSTERED (LLP_Id ASC)
)

INSERT INTO SGJD_ADM_TAB_TIPO_SESION VALUES ('Ordinaria')
INSERT INTO SGJD_ADM_TAB_TIPO_SESION VALUES ('Extraordinaria')

CREATE TABLE SGJD_ACT_TAB_SESION (
	LLP_Id INT NOT NULL IDENTITY (1,1),
	Numero INT NOT NULL,
	FechaHora DATETIME NOT NULL,
	LLF_IdTipoSesion INT NOT NULL,
	LLF_IdUsuario NVARCHAR (128) NOT NULL,
	CONSTRAINT LLP_Sesion PRIMARY KEY CLUSTERED (LLP_Id ASC),
	CONSTRAINT LLF_Sesion_TipoSesion_LLF_IdTipoSesion FOREIGN KEY (LLF_IdTipoSesion) REFERENCES SGJD_ADM_TAB_TIPO_SESION (LLP_Id),
	CONSTRAINT LLF_Sesion_Usuario_LLF_IdUsuario FOREIGN KEY (LLF_IdUsuario) REFERENCES SGJD_ADM_TAB_USUARIO (Id)
)

CREATE TABLE SGJD_ADM_TAB_ASISTENTE_SESION (
	LLP_Id INT NOT NULL IDENTITY (1, 1),
	LLF_IdSesion INT NOT NULL,
	LLF_IdUsuario NVARCHAR (128) NOT NULL,
	Presente BIT NOT NULL,
	HoraInicio DATETIME NOT NULL,
	HoraFin DATETIME NOT NULL,
	CONSTRAINT LLP_AsistenteSesion PRIMARY KEY CLUSTERED (LLP_Id ASC),
	CONSTRAINT LLF_AsistenteSesion_Sesion_LLF_IdSesion FOREIGN KEY (LLF_IdSesion) REFERENCES SGJD_ACT_TAB_SESION (LLP_Id),
	CONSTRAINT LLF_AsistenteSesion_Usuario_LLF_IdUsuario FOREIGN KEY (LLF_IdUsuario) REFERENCES SGJD_ADM_TAB_USUARIO (Id)
)

CREATE TABLE SGJD_ADM_TAB_OTRO_ASISTENTE_SESION (
	LLP_Id INT NOT NULL IDENTITY (1, 1),
	LLF_IdSesion INT NOT NULL,
	LLF_IdTipoUsuario INT NOT NULL,
	Nombre NVARCHAR (256) NOT NULL,
	Observacion NVARCHAR (256) NOT NULL,
	HoraInicio DATETIME NOT NULL,
	HoraFin DATETIME NOT NULL,
	CONSTRAINT LLP_OtroAsistenteSesion PRIMARY KEY CLUSTERED (LLP_Id ASC),
	CONSTRAINT LLF_OtroAsistenteSesion_Sesion_LLF_IdSesion FOREIGN KEY (LLF_IdSesion) REFERENCES SGJD_ACT_TAB_SESION (LLP_Id),
	CONSTRAINT LLF_OtroAsistencia_TipoUsuario_LLF_IdTipoUsuario FOREIGN KEY (LLF_IdTipoUsuario) REFERENCES SGJD_ADM_TAB_TIPO_USUARIO (LLP_Id)
)

CREATE TABLE SGJD_ACT_TAB_ORDEN_DIA (
	LLP_Id INT NOT NULL IDENTITY (1, 1),
	LLF_IdSesion INT NOT NULL,
	LLF_IdEstado INT NOT NULL,
	CONSTRAINT LLP_OrdenDia PRIMARY KEY CLUSTERED (LLP_Id ASC),
	CONSTRAINT LLF_OrdenDia_Sesion_LLF_IdSesion FOREIGN KEY (LLF_IdSesion) REFERENCES SGJD_ACT_TAB_SESION (LLP_Id),
	CONSTRAINT LLF_OrdenDia_Estado_LLF_IdEstado FOREIGN KEY (LLF_IdEstado) REFERENCES SGJD_ADM_TAB_ESTADO (LLP_Id)
)

CREATE TABLE SGJD_ACT_TAB_SECCION (
	LLP_Id INT NOT NULL IDENTITY (1, 1),
	Descripcion NVARCHAR (100) NOT NULL,
	CONSTRAINT LLP_Seccion PRIMARY KEY CLUSTERED (LLP_Id ASC)
)

CREATE TABLE SGJD_ACT_TAB_SECCION_ORDEN_DIA (
	LLP_Id INT NOT NULL IDENTITY (1, 1),
	LLF_IdOrdenDia INT NOT NULL,
	LLF_IdSeccion INT NOT NULL,
	CONSTRAINT LLP_SeccionOrdenDia PRIMARY KEY CLUSTERED (LLP_Id ASC),
	CONSTRAINT LLF_SeccionOrdenDia_OrdenDia_LFF_IdOrdenDia FOREIGN KEY (LLF_IdOrdenDia) REFERENCES SGJD_ACT_TAB_ORDEN_DIA (LLP_Id),
	CONSTRAINT LLF_SeccionOrdenDia_Seccion_LLF_IdSeccion FOREIGN KEY (LLF_IdSeccion) REFERENCES SGJD_ACT_TAB_SECCION (LLP_Id)
)

CREATE TABLE SGJD_ACT_TAB_TEMA (
	LLP_Id INT NOT NULL IDENTITY (1, 1),
	LLF_IdSeccion INT NOT NULL,
	LLF_IdOrdenDia INT NOT NULL,
	LLF_IdSesionEjecutada INT NULL,
	LLF_IdEstado INT NOT NULL,
	Titulo NVARCHAR (50) NOT NULL,	
	Resumen NVARCHAR (MAX) NOT NULL,
	CONSTRAINT LLP_Tema PRIMARY KEY CLUSTERED (LLP_Id ASC),
	CONSTRAINT LLF_Tema_Seccion_LLF_IdSeccion FOREIGN KEY (LLF_IdSeccion) REFERENCES SGJD_ACT_TAB_SECCION (LLP_Id),
	CONSTRAINT LLF_Tema_Sesion_LLF_IdSesionEjecutadan FOREIGN KEY (LLF_IdSesionEjecutada) REFERENCES SGJD_ACT_TAB_SESION (LLP_Id),
	CONSTRAINT LLF_Tema_Estado_LLF_IdEstado FOREIGN KEY (LLF_IdEstado) REFERENCES SGJD_ADM_TAB_ESTADO (LLP_Id),
	CONSTRAINT LLF_Tema_OrdenDia_LLF_idOrdenDia FOREIGN KEY (LLF_IdOrdenDia) REFERENCES SGJD_ACT_TAB_ORDEN_DIA (LLP_ID)
)

CREATE TABLE SGJD_ACT_TAB_TOMO (
	LLP_Id INT NOT NULL IDENTITY (1, 1),
	Numero INT NOT NULL,
	Nombre NVARCHAR (256),
	ObservaciónApertura NVARCHAR(4000) NOT NULL,
	ObservacionCierre NVARCHAR(4000) NULL,
 	CONSTRAINT LLP_Tomo PRIMARY KEY CLUSTERED (LLP_Id ASC)
)

CREATE TABLE SGJD_ACT_TAB_USUARIO_TOMO (
	LLF_IdTomo INT NOT NULL,
	LLF_IdUsuario NVARCHAR (128) NOT NULL,
	Fecha DATETIME NOT NULL,
	Accion NVARCHAR (50), --APERTURA / CIERRE
	CONSTRAINT LLP_TomoUsuario PRIMARY KEY CLUSTERED (LLF_IdTomo ASC, LLF_IdUsuario ASC),
	CONSTRAINT LLF_TomoUsuario_Usuario_LLF_IdTomo FOREIGN KEY (LLF_IdTomo) REFERENCES SGJD_ACT_TAB_TOMO(LLP_Id),
	CONSTRAINT LLF_TomoUsuario_Usuario_LLF_IdUsuario FOREIGN KEY (LLF_IdUsuario) REFERENCES SGJD_ADM_TAB_USUARIO(Id)
)

CREATE TABLE SGJD_ACT_TAB_ACTA (
	LLP_Id INT NOT NULL IDENTITY (1, 1),
	LLF_IdTipoObjeto INT NOT NULL,
	LLF_IdSesion INT NOT NULL,
	LLF_IdTomo INT NOT NULL,
	LLF_IdEstado INT NOT NULL,
	Numero INT NOT NULL,
	CONSTRAINT LLP_Acta PRIMARY KEY CLUSTERED (LLP_Id ASC),
	CONSTRAINT LLF_Acta_Sesion_LLF_IdSesion FOREIGN KEY (LLF_IdSesion) REFERENCES SGJD_ACT_TAB_SESION (LLP_Id),
	CONSTRAINT LLF_Acta_Tomo_LLF_IdTomo FOREIGN KEY (LLF_IdTomo) REFERENCES SGJD_ACT_TAB_TOMO(LLP_Id),
	CONSTRAINT LLF_Acta_Estado_LLF_IdEstado FOREIGN KEY (LLF_IdEstado) REFERENCES SGJD_ADM_TAB_ESTADO (LLP_Id),
	CONSTRAINT LLF_Acta_TipoObjeto_LLF_IdTipoObjeto FOREIGN KEY (LLF_IdTipoObjeto) REFERENCES SGJD_ADM_TAB_TIPO_OBJETO (LLP_Id)
)

CREATE TABLE SGJD_ACT_TAB_CAPITULO (
	LLP_Id INT NOT NULL IDENTITY (1, 1),
	LLF_IdActa INT NOT NULL,
	Titulo NVARCHAR (200) NOT NULL,
	Contenido NVARCHAR (MAX) NULL,
	CONSTRAINT LLP_Capitulo PRIMARY KEY CLUSTERED (LLP_Id ASC),
	CONSTRAINT LLF_Capitulo_Acta_LLF_IdActa FOREIGN KEY (LLF_IdActa) REFERENCES SGJD_ACT_TAB_ACTA (LLP_Id)
)

CREATE TABLE SGJD_ACT_TAB_ARTICULO (
	LLP_Id INT NOT NULL IDENTITY (1, 1),
	LLF_IdCapitulo INT NOT NULL,
	LLF_IdTema INT NULL,
	Numero INT NOT NULL,
	Titulo NVARCHAR (100) NOT NULL,
	Contenido NVARCHAR (MAX) NOT NULL,
	Confidencial BIT NOT NULL,
	CONSTRAINT LLP_Articulo PRIMARY KEY CLUSTERED (LLP_Id ASC),
	CONSTRAINT LLF_Articulo_Capitulo_LLF_IdCapitulo FOREIGN KEY (LLF_IdCapitulo) REFERENCES SGJD_ACT_TAB_CAPITULO (LLP_Id)
	CONSTRAINT LLF_Articulo_Tema_LLF_IdTema FOREIGN KEY (LLF_IdTema) REFERENCES SGJD_ACT_TAB_TEMA(LLP_Id)
)

CREATE TABLE SGJD_ACU_TAB_ACUERDO (
	LLP_Id INT NOT NULL IDENTITY (1, 1),
	LLF_IdArticulo INT NOT NULL,
	LLF_IdEstado INT NOT NULL,
	NumeroAcuerdo INT NOT NULL,
	Titulo NVARCHAR (1000) NOT NULL,
	Firme BIT NOT NULL,
	FechaFirmeza DATETIME NULL,
	Asunto NVARCHAR (1000) NOT NULL,
	NumeroVersion INT NOT NULL,
	Firma NVARCHAR (512) NULL,
	FechaNotificacion DATETIME NULL,
	FechaVencimiento DATETIME NULL,
	PlazoDias INT NULL,
	PorcentajeAvance DECIMAL NULL,
	CONSTRAINT LLP_Acuerdo PRIMARY KEY CLUSTERED (LLP_Id ASC),
	CONSTRAINT LLF_Acuerdo_Articulo_LLF_IdArticulo FOREIGN KEY (LLF_IdArticulo) REFERENCES SGJD_ACT_TAB_ARTICULO (LLP_Id),
	CONSTRAINT LLF_Acuerdo_Estado_LLF_IdEstado FOREIGN KEY (LLF_IdEstado) REFERENCES SGJD_ADM_TAB_ESTADO (LLP_Id)
)

CREATE TABLE SGJD_ACU_TAB_UNIDAD_ACUERDO (
	LLF_IdAcuerdo INT NOT NULL,
	LLF_IdUnidad INT NOT NULL,
	CONSTRAINT LLP_UnidadAcuerdo PRIMARY KEY CLUSTERED (LLF_IdAcuerdo ASC, LLF_IdUnidad ASC),
	CONSTRAINT LLF_UnidadAcuerdo_Acuerdo_LLF_IdAcuerdo FOREIGN KEY (LLF_IdAcuerdo) REFERENCES SGJD_ACU_TAB_ACUERDO (LLP_Id),
	CONSTRAINT LLF_UnidadAcuerdo_Unidad_LLF_IdUnidad FOREIGN KEY (LLF_IdUnidad) REFERENCES SGJD_ADM_TAB_UNIDAD (LLP_Id)
)

CREATE TABLE SGJD_ACU_TAB_PORTANTO (
	LLP_Id INT NOT NULL IDENTITY (1, 1),
	LLF_IdAcuerdo INT NOT NULL,
	Descripcion NVARCHAR (MAX) NOT NULL,
	CONSTRAINT LLP_PorTanto PRIMARY KEY CLUSTERED (LLP_Id ASC),
	CONSTRAINT LLF_PorTanto_Acuerdo_LLF_IdAcuerdo FOREIGN KEY (LLF_IdAcuerdo) REFERENCES SGJD_ACU_TAB_ACUERDO (LLP_Id)
)

CREATE TABLE SGJD_ACU_TAB_CONSIDERANDO (
	LLP_Id INT NOT NULL IDENTITY (1, 1),
	LLF_IdAcuerdo INT NOT NULL,
	Descripcion NVARCHAR (MAX) NOT NULL,
	CONSTRAINT LLP_Considerando PRIMARY KEY CLUSTERED (LLP_Id ASC),
	CONSTRAINT LLF_Considerando_Acuerdo_LLF_IdAcuerdo FOREIGN KEY (LLF_IdAcuerdo) REFERENCES SGJD_ACU_TAB_ACUERDO (LLP_Id)
)

CREATE TABLE SGJD_ACU_TAB_AVANCE (
	LLP_Id INT NOT NULL IDENTITY (1, 1),
	LLF_IdUsuario NVARCHAR (128) NOT NULL,
	LLF_IdAcuerdo INT NOT NULL,
	Descripcion NVARCHAR(MAX) NULL,
	CONSTRAINT LLP_Avance PRIMARY KEY CLUSTERED (LLP_Id ASC),
	CONSTRAINT LLF_Avance_Usuario_LLF_IdUsuario FOREIGN KEY (LLF_IdUsuario) REFERENCES SGJD_ADM_TAB_USUARIO (Id),
	CONSTRAINT LLF_Avance_Acuerdo_LLF_IdAcuerdo FOREIGN KEY (LLF_IdAcuerdo) REFERENCES SGJD_ACU_TAB_ACUERDO (LLP_Id)
)

CREATE TABLE SGJD_ADM_TAB_TELEFONO_USUARIO (
	LLP_Id INT NOT NULL IDENTITY (1, 1),
	LLF_IdUsuario NVARCHAR (128) NOT NULL,
	Numero NVARCHAR (20) NOT NULL,
	Extension NVARCHAR (10) NULL,
	CONSTRAINT LLP_TelefonoUsuario PRIMARY KEY CLUSTERED (LLP_Id ASC),
	CONSTRAINT LLF_TelefonoUsuario_Usuario_LLF_IdUsuario FOREIGN KEY (LLF_IdUsuario) REFERENCES SGJD_ADM_TAB_USUARIO (Id)
)

CREATE TABLE SGJD_ADM_TAB_CORREO_USUARIO (
	LLP_Id INT NOT NULL IDENTITY (1, 1),
	LLF_IdUsuario NVARCHAR (128) NOT NULL,
	Correo NVARCHAR(100),
	CONSTRAINT LLP_CorreoUsuario PRIMARY KEY CLUSTERED (LLP_Id ASC),
	CONSTRAINT LLF_CorreoUsuario_Usuario_LLF_IdUsuario FOREIGN KEY (LLF_IdUsuario) REFERENCES SGJD_ADM_TAB_USUARIO (Id)
)

CREATE TABLE SGJD_ADM_TAB_USUARIO_ARTICULO (
	LLF_IdArticulo INT NOT NULL,
	LLF_IdUsuario NVARCHAR (128) NOT NULL,
	CONSTRAINT LLP_UsuarioArticulo PRIMARY KEY CLUSTERED (LLF_IdArticulo, LLF_IdUsuario ASC),
	CONSTRAINT LLF_UsuarioArticulo_Articulo_LLF_IdArticulo FOREIGN KEY (LLF_IdArticulo) REFERENCES SGJD_ACT_TAB_ARTICULO (LLP_Id),
	CONSTRAINT LLF_UsuarioArticulo_Usuario_LLF_IdUsuario FOREIGN KEY (LLF_IdUsuario) REFERENCES SGJD_ADM_TAB_USUARIO (Id)
)

CREATE TABLE SGJD_ADM_TAB_ANOTACION (
	LLP_Id INT NOT NULL IDENTITY (1, 1),
	LLF_IdTipoObjeto INT NOT NULL,
	IdObjeto INT NOT NULL,
	LLF_IdEstado INT NOT NULL,
	Descripcion NVARCHAR (MAX) NOT NULL,
	CONSTRAINT LLP_Anotacion PRIMARY KEY CLUSTERED (LLP_Id ASC),
	CONSTRAINT LLF_Anotacion_TipoObjeto_LLF_IdTipoObjeto FOREIGN KEY (LLF_IdTipoObjeto) REFERENCES SGJD_ADM_TAB_TIPO_OBJETO (LLP_Id),
	CONSTRAINT LLF_Anotacion_Estado_LLF_IdEstado FOREIGN KEY (LLF_IdEstado) REFERENCES SGJD_ADM_TAB_ESTADO (LLP_Id)
)

CREATE TABLE SGJD_ADM_TAB_REPOSITORIO (
	LLP_Id INT NOT NULL IDENTITY (1, 1),
	Nombre NVARCHAR (50) NOT NULL,
	Ruta NVARCHAR (50) NOT NULL,
	CONSTRAINT LLP_Repositorio PRIMARY KEY CLUSTERED (LLP_Id ASC)
)

CREATE TABLE SGJD_ADM_TAB_TIPO_ARCHIVO (
	LLP_Id INT NOT NULL IDENTITY (1, 1),
	Nombre NVARCHAR(10) NOT NULL,
	Descripcion NVARCHAR(255) NOT NULL,
	CONSTRAINT LLP_TIPO_ARCHIVO PRIMARY KEY CLUSTERED (LLP_Id ASC)
)

CREATE TABLE SGJD_ADM_TAB_ARCHIVO_ADJUNTO(
	LLP_Id INT NOT NULL IDENTITY (1, 1),
	LLF_IdTipoObjeto INT NOT NULL,
	LLF_IdRepositorio INT NOT NULL,
	LLF_IdTipoArchivo INT NOT NULL,
	IdObjeto INT NOT NULL,
	Observacion NVARCHAR(MAX) NULL,
	UrlArchivo NVARCHAR(100) NOT NULL,
	CONSTRAINT LLP_ArchivoAdjunto PRIMARY KEY CLUSTERED (LLP_Id ASC),
	CONSTRAINT LLF_ArchivoAdjunto_TipoObjeto_LLF_IdTipoObjeto FOREIGN KEY (LLF_IdTipoObjeto) REFERENCES SGJD_ADM_TAB_TIPO_OBJETO (LLP_Id),
	CONSTRAINT LLF_ArchivoAdjunto_Ruta_LLF_IdRepositorio FOREIGN KEY (LLF_IdRepositorio) REFERENCES SGJD_ADM_TAB_REPOSITORIO (LLP_Id),
	CONSTRAINT LLF_ARCHIVO_ADJUNTO_LLF_TIPO_ARCHIVO FOREIGN KEY (LLF_IdTipoArchivo) REFERENCES SGJD_ADM_TAB_TIPO_ARCHIVO (LLP_Id)
)

CREATE TABLE SGJD_ADM_TAB_BITACORA (
	LLP_Id INT NOT NULL IDENTITY (1, 1),
	LLF_IdUsuario NVARCHAR (128) NOT NULL,
	FechaHora DATETIME NOT NULL,
	Accion NVARCHAR (MAX) NOT NULL,
	ValorAntiguo NVARCHAR (MAX) NOT NULL,
	ValorNuevo NVARCHAR (MAX) NOT NULL,
	DireccionIP NVARCHAR (50) NOT NULL,
	DescripcionDispositivo NVARCHAR (100) NOT NULL,
	SeccionSistema NVARCHAR (100) NOT NULL,
	CONSTRAINT LLP_Bitacora PRIMARY KEY CLUSTERED (LLP_Id ASC),
	CONSTRAINT LLF_Bitacora_Usuario_LLF_IdUsuario FOREIGN KEY (LLF_IdUsuario) REFERENCES SGJD_ADM_TAB_USUARIO (Id)
)

CREATE TABLE SGJD_ADM_TAB_RESPALDO (
	LLP_Id INT NOT NULL IDENTITY (1, 1),
	LLF_IdUsuario NVARCHAR (128) NOT NULL,
	FechaHora DATETIME NOT NULL,
	NombreRespaldo NVARCHAR (100) NOT NULL,
	URLArchivoBD NVARCHAR (100) NOT NULL,
	URLArchivoRepositorio NVARCHAR (999) NOT NULL,
	CONSTRAINT LLP_Respaldo PRIMARY KEY CLUSTERED (LLP_Id ASC),
	CONSTRAINT LLF_Respaldo_Usuario_LLF_IdUsuario FOREIGN KEY (LLF_IdUsuario) REFERENCES SGJD_ADM_TAB_USUARIO (Id)
)

CREATE TABLE SGJD_ADM_TAB_PARAMETROS_GENERALES (
	LLP_Id INTEGER IDENTITY (1,1) NOT NULL,
	Nombre NVARCHAR (50) NOT NULL,
	Valor NVARCHAR (50) NOT NULL,
	Descripcion NVARCHAR (200) NOT NULL,
	Tipo NVARCHAR (20) NOT NULL,
	CONSTRAINT LLP_PARAMETROS_GENERALES PRIMARY KEY CLUSTERED (LLP_Id ASC)
)

CREATE TABLE SGJD_ADM_TAB_CONFIGURACION_AVISOS (
	LLP_Id INTEGER IDENTITY (1,1) NOT NULL,
	LLF_IdUnidad INTEGER NULL,
	Nombre NVARCHAR (100) NOT NULL,
	Mensaje NVARCHAR (MAX) NOT NULL,
	TipoDestinatario NVARCHAR (50) NOT NULL,
	Tipo NVARCHAR (20) NOT NULL,
	CONSTRAINT LLP_Configuracion_Avisos PRIMARY KEY CLUSTERED (LLP_Id ASC),
	CONSTRAINT LLF_CONFIGURACION_AVISOS_UNIDAD_LLF_IdUnidad FOREIGN KEY (LLF_IdUnidad) REFERENCES SGJD_ADM_TAB_UNIDAD (LLP_Id)
)

CREATE TABLE SGJD_ADM_TAB_DESTINATARIOS_AVISOS (
	LLF_IdAviso INTEGER NOT NULL,
	LLF_IdUsuario NVARCHAR (128) NOT NULL,
	Prueba NVARCHAR (1) NULL,
	CONSTRAINT LLP_DESTINATARIOS_AVISOS PRIMARY KEY CLUSTERED (LLF_IdAviso, LLF_IdUsuario),
	CONSTRAINT LLF_Destinatarios_Avisos_ConfiguracionAvisos_LLF_IdAviso FOREIGN KEY (LLF_IdAviso) REFERENCES SGJD_ADM_TAB_CONFIGURACION_AVISOS (LLP_Id),
	CONSTRAINT LLF_Destinatarios_Avisos_Usuario_LLF_IdUsuario FOREIGN KEY (LLF_IdUsuario) REFERENCES SGJD_ADM_TAB_USUARIO (Id)
) 

CREATE TABLE SGJD_ADM_TAB_NOTIFICACIONES (
	LLP_Id int NOT NULL IDENTITY (1,1),
	LLF_Usuario NVARCHAR(128),
	Mensaje NVARCHAR(MAX),
	FechaHora DATETIME,
	CONSTRAINT LLP_Notificaciones PRIMARY KEY CLUSTERED (LLP_Id ASC),
	CONSTRAINT LLF_Notificaciones_Usuario_LLF_Usuario FOREIGN KEY (LLF_Usuario) REFERENCES SGJD_ADM_TAB_USUARIO(Id)
)

CREATE TABLE SGJD_ADM_TAB_ENCABEZADO_PIEPAGINA (
	LLP_Id INT NOT NULL IDENTITY (1, 1),
	LLF_IdTipoObjeto INT NOT NULL,
	Encabezado NVARCHAR (max) NULL,
	PiePagina NVARCHAR (max) NULL,	
	CONSTRAINT LLP_EncabezadoPiepagina PRIMARY KEY CLUSTERED (LLP_Id ASC),
	CONSTRAINT LLF_EncabezadoPiepagina_TipoObjeto_LLF_IdTipoObjeto FOREIGN KEY (LLF_IdTipoObjeto) REFERENCES SGJD_ADM_TAB_TIPO_OBJETO (LLP_Id)
)

CREATE PROCEDURE [dbo].[SGJD_ACT_PRO_FILTRO_PALABRA_CLAVE_ACTAS](@Palabra nvarchar(250))

AS 

SELECT DISTINCT Acta.LLP_Id as Id, Acta.LLF_IdTomo, Acta.LLF_IdSesion, Acta.LLF_IdEstado,  Acta.Numero as 'NumeroActa', Sesion.Numero as 'NumeroSesion', TipoSesion.Descripcion as 'tipoSesionDescripcion',
Sesion.FechaHora as 'FechaHoraSesion', Tomo.Numero as 'NumeroTomo', Tomo.Nombre as 'NombreTomo', Estado.Descripcion as 'DescripcionEstado' FROM SGJD_ACT_TAB_ACTA Acta
INNER JOIN SGJD_ACT_TAB_CAPITULO Capitulo ON  Capitulo.LLF_IdActa = Acta.LLP_Id 
LEFT JOIN SGJD_ACT_TAB_ARTICULO Articulo ON  Articulo.LLF_IdCapitulo = Capitulo.LLP_Id 
LEFT JOIN SGJD_ACU_TAB_ACUERDO Acuerdo ON    Acuerdo.LLF_IdArticulo = Articulo.LLP_Id
LEFT JOIN SGJD_ACT_TAB_SESION Sesion ON    Sesion.LLP_Id = Acta.LLF_IdSesion
LEFT JOIN SGJD_ADM_TAB_TIPO_SESION TipoSesion ON  TipoSesion.LLP_Id = Sesion.LLF_IdTipoSesion
LEFT JOIN SGJD_ACT_TAB_TOMO Tomo ON    Tomo.LLP_Id = Acta.LLF_IdTomo
LEFT JOIN SGJD_ADM_TAB_ESTADO Estado ON    Estado.LLP_Id = Acta.LLF_IdEstado
WHERE  Capitulo.Titulo LIKE '%'+@Palabra+'%' 
OR Capitulo.Contenido LIKE '%'+@Palabra+'%' 
OR Articulo.Titulo LIKE '%'+@Palabra+'%'  
OR Articulo.Contenido LIKE '%'+@Palabra+'%'  
OR Acuerdo.Titulo LIKE '%'+@Palabra+'%' 


--CREATE TABLE SGJD_ACT_TAB_IMAGEN_ARTICULO (
--LLP_Id INT IDENTITY PRIMARY KEY,
--LLF_IdArticulo INT NOT NULL,
--Descripcion NVARCHAR (128),
--UrlArchivo NVARCHAR (128)
--);

--ALTER TABLE SGJD_ACT_TAB_IMAGEN_ARTICULO
--ADD CONSTRAINT LLP_Articulo_Articulo_LLF_IdArticulo FOREIGN KEY (LLF_IdArticulo) REFERENCES SGJD_ACT_TAB_ARTICULO (LLP_Id)

CREATE PROCEDURE SGJD_ACT_PRO_FILTRO_PALABRA_CLAVE_ACUERDOS(@Palabra nvarchar(250))

AS 

SELECT DISTINCT Acuerdo.LLP_Id as LLP_Id, Acuerdo.Asunto as Asunto, Acuerdo.Detalle as Detalle, Acuerdo.FechaFirmeza as FechaFirmesa,
Acuerdo.FechaNotificacion as FechaNotificacion, Acuerdo.FechaVencimiento as FechaVencimiento, Acuerdo.Firma as Firma, Acuerdo.Firme as Firme,
Acuerdo.LLF_IdArticulo as LLF_IdArticulo, Acuerdo.LLF_IdEstado as LLF_IdEstado, Acuerdo.NumeroAcuerdo as NumeroAcuerdo, Acuerdo.NumeroVersion as NumeroVersion,
Acuerdo.Observaciones as Observaciones, Acuerdo.PlazoDias as PlazoDias, Acuerdo.PorcentajeAvance as PorcentajeAvance, Acuerdo.Titulo as Titulo    
FROM SGJD_ACU_TAB_ACUERDO Acuerdo
LEFT JOIN SGJD_ACU_TAB_PORTANTO PorTanto ON  PorTanto.LLF_IdAcuerdo = Acuerdo.LLP_Id 
LEFT JOIN SGJD_ACU_TAB_CONSIDERANDO Considerando ON  Considerando.LLF_IdAcuerdo = Acuerdo.LLP_Id 
WHERE Acuerdo.Asunto LIKE '%'+@Palabra+'%' 
OR Acuerdo.Detalle LIKE '%'+@Palabra+'%' 
OR Acuerdo.Titulo LIKE '%'+@Palabra+'%'
OR Acuerdo.Observaciones LIKE '%'+@Palabra+'%' 
OR PorTanto.Descripcion LIKE '%'+@Palabra+'%'  
OR Considerando.Descripcion LIKE '%'+@Palabra+'%'  


USE [SGJD]
GO
/****** Object:  StoredProcedure [dbo].[[SGJD_ACU_PRO_OBTENER_ACUERDO_POR_ARTICULO_ENFIRME]]    Script Date: 16/9/2019 11:50:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--SP para realizar extraer un acuerdo con su considerando y por tanto para cada articulo por id articulo
CREATE PROCEDURE [dbo].[SGJD_ACU_PRO_OBTENER_ACUERDO_POR_ARTICULO_ENFIRME](@Articulo int)

AS 

SELECT Acuerdo.Titulo as TituloAcuerdo, Considerando.LLP_Id as IdConsiderando, Considerando.LLF_IdAcuerdo as LLF_IdAcuerdoConsiderando , Considerando.Descripcion as DescripcionConsiderando , PorTanto.LLP_Id as IdPorTanto, PorTanto.LLF_IdAcuerdo as LLF_IdAcuerdoPorTanto, PorTanto.Descripcion as DescripcionPorTanto
FROM SGJD_ACT_TAB_ARTICULO Articulo
INNER JOIN SGJD_ACU_TAB_ACUERDO Acuerdo  ON Acuerdo.LLF_IdArticulo = Articulo.LLP_Id
INNER JOIN SGJD_ACU_TAB_PORTANTO PorTanto  ON PorTanto.LLF_IdAcuerdo = Acuerdo.LLP_Id
INNER JOIN SGJD_ACU_TAB_CONSIDERANDO Considerando  ON Considerando.LLF_IdAcuerdo = Acuerdo.LLP_Id
WHERE Articulo.LLP_Id = @Articulo AND
Acuerdo.Firme = 1


USE [SGJD]
GO
/****** Object:  StoredProcedure [dbo].[SGJD_ACU_PRO_OBTENER_ACUERDO_POR_ARTICULO]    Script Date: 16/9/2019 11:50:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--SP para realizar extraer un acuerdo con su considerando y por tanto para cada articulo por id articulo
CREATE PROCEDURE [dbo].[SGJD_ACU_PRO_OBTENER_ACUERDO_POR_ARTICULO](@Articulo int)

AS 

SELECT Acuerdo.Titulo as TituloAcuerdo, Considerando.LLP_Id as IdConsiderando, Considerando.LLF_IdAcuerdo as LLF_IdAcuerdoConsiderando , Considerando.Descripcion as DescripcionConsiderando , PorTanto.LLP_Id as IdPorTanto, PorTanto.LLF_IdAcuerdo as LLF_IdAcuerdoPorTanto, PorTanto.Descripcion as DescripcionPorTanto
FROM SGJD_ACT_TAB_ARTICULO Articulo
INNER JOIN SGJD_ACU_TAB_ACUERDO Acuerdo  ON Acuerdo.LLF_IdArticulo = Articulo.LLP_Id
INNER JOIN SGJD_ACU_TAB_PORTANTO PorTanto  ON PorTanto.LLF_IdAcuerdo = Acuerdo.LLP_Id
INNER JOIN SGJD_ACU_TAB_CONSIDERANDO Considerando  ON Considerando.LLF_IdAcuerdo = Acuerdo.LLP_Id
WHERE Articulo.LLP_Id = @Articulo