// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:SGJD_INA.Models.Core.Implementation.RepositorioLogic.CrearCarpetaRepositorio(SGJD_INA.Models.Entities.Repositorio)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~M:SGJD_INA.MvcApplication.Application_PreSendRequestHeaders(System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1056:Uri properties should not be strings", Justification = "<Pending>", Scope = "member", Target = "~P:SGJD_INA.Models.Entities.Audio.UrlAudio")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2208:Instantiate argument exceptions correctly", Justification = "<Pending>", Scope = "member", Target = "~M:SGJD_INA.Controllers.ParametrosGeneralesController.Editar(System.String)~System.Threading.Tasks.Task{System.Web.Mvc.ActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:SGJD_INA.Models.Helpers.Funciones.IsValidEmail(System.String)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:SGJD_INA.Models.Helpers.Funciones.IsDate(System.String)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:SGJD_INA.Models.Helpers.Funciones.JoinStringToDateTime(System.DateTime,System.String)~System.DateTime")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:SGJD_INA.Models.Helpers.Funciones.StringToDateTime(System.String)~System.DateTime")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:SGJD_INA.Models.Helpers.Funciones.ObtenerIP(System.Web.HttpRequestBase)~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1054:Uri parameters should not be strings", Justification = "<Pending>", Scope = "member", Target = "~M:SGJD_INA.ApplicationEmailService.ConfigurarMensajeCorreo(System.String,System.String,System.String,System.String,System.String)~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:SGJD_INA.Models.Core.Implementation.BitacoraLogic.EscribirErrorEnArchivoLog(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0054:Use compound assignment", Justification = "<Pending>", Scope = "member", Target = "~M:SGJD_INA.Models.Core.Implementation.AcuerdoLogic.ObtenerTodosPorRangoFechaAsync(System.DateTime,System.DateTime)~System.Threading.Tasks.Task{System.Collections.Generic.IEnumerable{SGJD_INA.Models.Entities.Acuerdo}}")]
